# https://gist.github.com/doctor-g/96c69a05cb45db1fc3b911b3f7436a65
# https://codewithandrea.com/articles/flutter-web-github-pages/
# https://dev.to/janux_de/automatically-publish-a-flutter-web-app-on-github-pages-3m1f
# https://www.immadisairaj.dev/blog/2022/github-actions-for-flutter-web/
name: Flutter Web Deploy
on:
  push:
    branches:
      - main
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter build web --release --base-href /${{ github.event.repository.name }}/
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions for '${{ github.event.repository.name }}'"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
